### ISSUE TITLE
hi i have question

### ISSUE THREAD

**Issue by TheC0mpany** [Catalyst-42/chest-collection#1]
hi i have question, привет, может у тебя есть matrix, discord, xmpp? Если да мог бы ты скинуть?

**Comment by Catalyst-42** [comment]
Discord: Catalyst#3776, только вот не понимаю зачем

**Comment by Catalyst-42** [comment]
It's just a site with images

**Comment by TheC0mpany** [comment]
don't ask in other people repos about it, ask in mine repos about it
